# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘WMFriendCircle’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Troops

  target ‘WMFriendCircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target ‘WMFriendCircleUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'Masonry','0.6.3'
pod 'SDWebImage','3.8.0'

pod 'MJExtension'

pod 'TZImagePickerController'

pod 'MWPhotoBrowser'

end
